-- Update all cover_img paths to use simple ID-based filenames
-- Generated based on best available image for each food

UPDATE food SET cover_img = "/images/foods/1.jpg" WHERE food_id = 1; -- 有机小番茄 500g
UPDATE food SET cover_img = "/images/foods/2.jpg" WHERE food_id = 2; -- 新鲜西蓝花 约400g
UPDATE food SET cover_img = "/images/foods/3.jpg" WHERE food_id = 3; -- 云南高原蓝莓 125g*2盒
UPDATE food SET cover_img = "/images/foods/4.jpg" WHERE food_id = 4; -- 应季青苹果 4个装
UPDATE food SET cover_img = "/images/foods/5.jpg" WHERE food_id = 5; -- 农家土鸡蛋 10枚装
UPDATE food SET cover_img = "/images/foods/6.jpg" WHERE food_id = 6; -- 新鲜胡萝卜 2根装
UPDATE food SET cover_img = "/images/foods/7.jpg" WHERE food_id = 7; -- 海南金煌芒果 2个
UPDATE food SET cover_img = "/images/foods/8.jpg" WHERE food_id = 8; -- 新鲜菠菜 300g
UPDATE food SET cover_img = "/images/foods/9.jpg" WHERE food_id = 9; -- 冷鲜五花肉 300g
UPDATE food SET cover_img = "/images/foods/10.jpg" WHERE food_id = 10; -- 德青源鲜鸡蛋 12枚
UPDATE food SET cover_img = "/images/foods/11.jpg" WHERE food_id = 11; -- 即食鸡胸肉 100g*3袋
UPDATE food SET cover_img = "/images/foods/12.jpg" WHERE food_id = 12; -- 蒙牛纯牛奶 250ml*16盒
UPDATE food SET cover_img = "/images/foods/13.jpg" WHERE food_id = 13; -- 科尔沁牛肉馅 250g
UPDATE food SET cover_img = "/images/foods/14.jpg" WHERE food_id = 14; -- 光明原味酸奶 180g*4杯
UPDATE food SET cover_img = "/images/foods/15.jpg" WHERE food_id = 15; -- 南京盐水鸭即食 300g
UPDATE food SET cover_img = "/images/foods/16.jpg" WHERE food_id = 16; -- 鹌鹑蛋 20枚装
UPDATE food SET cover_img = "/images/foods/17.jpg" WHERE food_id = 17; -- 新鲜虾仁 200g
UPDATE food SET cover_img = "/images/foods/18.jpg" WHERE food_id = 18; -- 里昂那火腿片 100g
UPDATE food SET cover_img = "/images/foods/19.jpg" WHERE food_id = 19; -- 三只松鼠夏威夷果 260g
UPDATE food SET cover_img = "/images/foods/20.jpg" WHERE food_id = 20; -- 奥利奥夹心饼干 388g
UPDATE food SET cover_img = "/images/foods/21.jpg" WHERE food_id = 21; -- 旺旺雪饼 400g
UPDATE food SET cover_img = "/images/foods/22.jpg" WHERE food_id = 22; -- 洽洽香瓜子 308g
UPDATE food SET cover_img = "/images/foods/23.jpg" WHERE food_id = 23; -- 良品铺子猪肉脯 200g
UPDATE food SET cover_img = "/images/foods/24.jpg" WHERE food_id = 24; -- 上好佳虾条 60g*6包
UPDATE food SET cover_img = "/images/foods/25.jpg" WHERE food_id = 25; -- 德芙巧克力 252g
UPDATE food SET cover_img = "/images/foods/26.jpg" WHERE food_id = 26; -- 日本豆乳威化饼干 108g
UPDATE food SET cover_img = "/images/foods/27.jpg" WHERE food_id = 27; -- mixed 综合坚果 500g
UPDATE food SET cover_img = "/images/foods/28.jpg" WHERE food_id = 28; -- 韩国海苔 12包
UPDATE food SET cover_img = "/images/foods/29.jpg" WHERE food_id = 29; -- 金丝猴奶糖 200g
UPDATE food SET cover_img = "/images/foods/30.jpg" WHERE food_id = 30; -- 士力架花生巧克力 440g
UPDATE food SET cover_img = "/images/foods/31.jpg" WHERE food_id = 31; -- 金龙鱼一级大豆油 5L
UPDATE food SET cover_img = "/images/foods/32.jpg" WHERE food_id = 32; -- 海天金标生抽 500ml
UPDATE food SET cover_img = "/images/foods/33.jpg" WHERE food_id = 33; -- 五常大米 5kg
UPDATE food SET cover_img = "/images/foods/34.jpg" WHERE food_id = 34; -- 李锦记蚝油 510g
UPDATE food SET cover_img = "/images/foods/35.jpg" WHERE food_id = 35; -- 鲁花花生油 5S压榨 5L
UPDATE food SET cover_img = "/images/foods/36.jpg" WHERE food_id = 36; -- 千禾零添加酱油 500ml
UPDATE food SET cover_img = "/images/foods/37.jpg" WHERE food_id = 37; -- 恒顺香醋 500ml
UPDATE food SET cover_img = "/images/foods/38.jpg" WHERE food_id = 38; -- 福临门东北珍珠米 10kg
UPDATE food SET cover_img = "/images/foods/39.jpg" WHERE food_id = 39; -- 三全水饺 猪肉白菜 1kg
UPDATE food SET cover_img = "/images/foods/40.jpg" WHERE food_id = 40; -- 湾仔码头手工水饺 540g
UPDATE food SET cover_img = "/images/foods/41.jpg" WHERE food_id = 41; -- 海底捞自热火锅 麻辣牛肉 400g
UPDATE food SET cover_img = "/images/foods/42.jpg" WHERE food_id = 42; -- 思念猪肉灌汤水饺 450g
UPDATE food SET cover_img = "/images/foods/43.jpg" WHERE food_id = 43; -- 新疆阿克苏冰糖心苹果 4个
UPDATE food SET cover_img = "/images/foods/44.jpg" WHERE food_id = 44; -- 山东大葱 2根
UPDATE food SET cover_img = "/images/foods/45.jpg" WHERE food_id = 45; -- 荷兰土豆 2.5kg
UPDATE food SET cover_img = "/images/foods/46.jpg" WHERE food_id = 46; -- 云南高原土豆 2kg
UPDATE food SET cover_img = "/images/foods/47.jpg" WHERE food_id = 47; -- 甘肃定西土豆 3kg
UPDATE food SET cover_img = "/images/foods/48.jpg" WHERE food_id = 48; -- 东北糯玉米 5穗
UPDATE food SET cover_img = "/images/foods/49.jpg" WHERE food_id = 49; -- 有机红薯 1.5kg
UPDATE food SET cover_img = "/images/foods/50.jpg" WHERE food_id = 50; -- 新鲜莲藕 2节
UPDATE food SET cover_img = "/images/foods/51.jpg" WHERE food_id = 51; -- 香菇 300g
UPDATE food SET cover_img = "/images/foods/52.jpg" WHERE food_id = 52; -- 新鲜银耳 200g
UPDATE food SET cover_img = "/images/foods/53.jpg" WHERE food_id = 53; -- 紫甘蓝 1颗
UPDATE food SET cover_img = "/images/foods/54.jpg" WHERE food_id = 54; -- 娃娃菜 3棵
UPDATE food SET cover_img = "/images/foods/55.jpg" WHERE food_id = 55; -- 荷兰小黄瓜 6根
UPDATE food SET cover_img = "/images/foods/56.jpg" WHERE food_id = 56; -- 海南贵妃芒 3个
UPDATE food SET cover_img = "/images/foods/57.jpg" WHERE food_id = 57; -- 越南红心火龙果 2个
UPDATE food SET cover_img = "/images/foods/58.jpg" WHERE food_id = 58; -- 丹麦皇冠猪排 300g
UPDATE food SET cover_img = "/images/foods/59.jpg" WHERE food_id = 59; -- 澳洲进口牛腩 500g
UPDATE food SET cover_img = "/images/foods/60.jpg" WHERE food_id = 60; -- 圣迪乐村鸡蛋 30枚
UPDATE food SET cover_img = "/images/foods/61.jpg" WHERE food_id = 61; -- 荷斯坦纯牛奶 1L*2盒
UPDATE food SET cover_img = "/images/foods/62.jpg" WHERE food_id = 62; -- 大希地虾仁 200g*2袋
UPDATE food SET cover_img = "/images/foods/63.jpg" WHERE food_id = 63; -- 荷美尔培根 200g*2包
UPDATE food SET cover_img = "/images/foods/64.jpg" WHERE food_id = 64; -- 王致和腐乳 340g*2瓶
UPDATE food SET cover_img = "/images/foods/65.jpg" WHERE food_id = 65; -- 老干妈风味鸡油辣子 280g
UPDATE food SET cover_img = "/images/foods/66.jpg" WHERE food_id = 66; -- 北纬45°纯驼乳粉 300g
UPDATE food SET cover_img = "/images/foods/67.jpg" WHERE food_id = 67; -- IFF天然香草精 60ml
UPDATE food SET cover_img = "/images/foods/68.jpg" WHERE food_id = 68; -- 可生食鲜鸡蛋 20枚
UPDATE food SET cover_img = "/images/foods/69.jpg" WHERE food_id = 69; -- 进口车达奶酪片 200g*2包
UPDATE food SET cover_img = "/images/foods/70.jpg" WHERE food_id = 70; -- 东北笨鸡蛋 20枚
UPDATE food SET cover_img = "/images/foods/71.jpg" WHERE food_id = 71; -- 鸡腿肉 500g
UPDATE food SET cover_img = "/images/foods/72.jpg" WHERE food_id = 72; -- IFF黄油块 227g*2块
UPDATE food SET cover_img = "/images/foods/73.jpg" WHERE food_id = 73; -- 山姆Member
UPDATE food SET cover_img = "/images/foods/74.jpg" WHERE food_id = 74; -- 白色恋人白巧克力夹心饼干 12枚
UPDATE food SET cover_img = "/images/foods/75.jpg" WHERE food_id = 75; -- Lindt瑞士莲黑巧克力 100g*2块
UPDATE food SET cover_img = "/images/foods/76.jpg" WHERE food_id = 76; -- 乐事大礼包 528g（薯片组合）
UPDATE food SET cover_img = "/images/foods/77.jpg" WHERE food_id = 77; -- 卫龙大面筋 65g*10包
UPDATE food SET cover_img = "/images/foods/78.jpg" WHERE food_id = 78; -- 溜溜梅话梅 100g*3袋
UPDATE food SET cover_img = "/images/foods/79.jpg" WHERE food_id = 79; -- 波力海苔 12包
UPDATE food SET cover_img = "/images/foods/80.jpg" WHERE food_id = 80; -- 雀巢脆脆鲨 216g（12根）
UPDATE food SET cover_img = "/images/foods/81.jpg" WHERE food_id = 81; -- 稻香村枣花酥 180g（3块）
UPDATE food SET cover_img = "/images/foods/82.jpg" WHERE food_id = 82; -- 金丝猴麦丽素 128g
UPDATE food SET cover_img = "/images/foods/83.jpg" WHERE food_id = 83; -- 好丽友蛋黄派 168g（6枚）
UPDATE food SET cover_img = "/images/foods/84.jpg" WHERE food_id = 84; -- 天喔煮瓜子 280g*2包
UPDATE food SET cover_img = "/images/foods/85.jpg" WHERE food_id = 85; -- 蒙都牛肉干 200g
UPDATE food SET cover_img = "/images/foods/86.jpg" WHERE food_id = 86; -- 来伊份鸭胗 200g
UPDATE food SET cover_img = "/images/foods/87.jpg" WHERE food_id = 87; -- 周黑鸭锁鲜装 300g
UPDATE food SET cover_img = "/images/foods/88.jpg" WHERE food_id = 88; -- 中粮福临门稻米油 5L
UPDATE food SET cover_img = "/images/foods/89.jpg" WHERE food_id = 89; -- 千禾有机糙米 2.5kg
UPDATE food SET cover_img = "/images/foods/90.jpg" WHERE food_id = 90; -- 海底捞麻辣香锅底料 200g*2包
UPDATE food SET cover_img = "/images/foods/91.jpg" WHERE food_id = 91; -- 恒顺香醋 500ml
UPDATE food SET cover_img = "/images/foods/92.jpg" WHERE food_id = 92; -- 老干妈风味豆豉油辣子 210g
UPDATE food SET cover_img = "/images/foods/93.jpg" WHERE food_id = 93; -- 古船标准粉 5kg
UPDATE food SET cover_img = "/images/foods/94.jpg" WHERE food_id = 94; -- 多力葵花籽油 5L
UPDATE food SET cover_img = "/images/foods/95.jpg" WHERE food_id = 95; -- 东北黑木耳 150g
UPDATE food SET cover_img = "/images/foods/96.jpg" WHERE food_id = 96; -- 紫菜干 40g*3包
UPDATE food SET cover_img = "/images/foods/97.jpg" WHERE food_id = 97; -- 海底捞牛油火锅底料 150g*2包
UPDATE food SET cover_img = "/images/foods/98.jpg" WHERE food_id = 98; -- 广州酒家利口福核桃包 360g（6个）
UPDATE food SET cover_img = "/images/foods/99.jpg" WHERE food_id = 99; -- 日清蒲烧鳗鱼 120g*2条
UPDATE food SET cover_img = "/images/foods/100.jpg" WHERE food_id = 100; -- 必品阁王饺子 玉米猪肉 600g
UPDATE food SET cover_img = "/images/foods/101.jpg" WHERE food_id = 101; -- 农心辛拉面 120g*5包
UPDATE food SET cover_img = "/images/foods/102.jpg" WHERE food_id = 102; -- 海底捞自热米饭 宫保鸡丁 300g
UPDATE food SET cover_img = "/images/foods/103.jpg" WHERE food_id = 103; -- 缸鸭狗速冻宁波汤圆 400g（24个）
UPDATE food SET cover_img = "/images/foods/104.jpg" WHERE food_id = 104; -- 安井奶黄包 240g（6个）
UPDATE food SET cover_img = "/images/foods/105.jpg" WHERE food_id = 105; -- 大希地披萨底胚 4片装
UPDATE food SET cover_img = "/images/foods/106.jpg" WHERE food_id = 106; -- 三全卡通包 260g（12个）
UPDATE food SET cover_img = "/images/foods/107.jpg" WHERE food_id = 107; -- 日清意面酱 190g*3包组合
UPDATE food SET cover_img = "/images/foods/108.jpg" WHERE food_id = 108; -- 眉州东坡卤香牛肉 200g
UPDATE food SET cover_img = "/images/foods/109.jpg" WHERE food_id = 109; -- 必品阁泡菜煎饼预拌粉 400g
UPDATE food SET cover_img = "/images/foods/110.jpg" WHERE food_id = 110; -- 湾仔码头上素小云吞 480g
UPDATE food SET cover_img = "/images/foods/111.jpg" WHERE food_id = 111; -- 白家陈记酸辣粉 262g*3桶
UPDATE food SET cover_img = "/images/foods/112.jpg" WHERE food_id = 112; -- 海底捞番茄火锅底料 200g*2包
UPDATE food SET cover_img = "/images/foods/113.jpg" WHERE food_id = 113; -- 元气森林无糖气泡水 480ml*6瓶
UPDATE food SET cover_img = "/images/foods/114.jpg" WHERE food_id = 114; -- 农夫山泉17.5° NFC橙汁 300ml*4瓶
UPDATE food SET cover_img = "/images/foods/115.jpg" WHERE food_id = 115; -- 雀巢咖啡醇香拿铁 268ml*6瓶
UPDATE food SET cover_img = "/images/foods/116.jpg" WHERE food_id = 116; -- 农夫山泉东方树叶茉莉花茶 500ml*6瓶
UPDATE food SET cover_img = "/images/foods/117.jpg" WHERE food_id = 117; -- 伊利安慕希希腊风味酸奶 205g*12盒
UPDATE food SET cover_img = "/images/foods/118.jpg" WHERE food_id = 118; -- 巴黎水气泡水 330ml*6瓶
UPDATE food SET cover_img = "/images/foods/119.jpg" WHERE food_id = 119; -- 百岁山矿泉水 570ml*24瓶
UPDATE food SET cover_img = "/images/foods/120.jpg" WHERE food_id = 120; -- 王老吉凉茶 310ml*12罐
UPDATE food SET cover_img = "/images/foods/121.jpg" WHERE food_id = 121; -- 乌龙茶饮料 500ml*6瓶
UPDATE food SET cover_img = "/images/foods/122.jpg" WHERE food_id = 122; -- 莫里斯蒂莫特椰子水 330ml*6瓶
UPDATE food SET cover_img = "/images/foods/123.jpg" WHERE food_id = 123; -- 旺仔牛奶 125ml*24盒
UPDATE food SET cover_img = "/images/foods/124.jpg" WHERE food_id = 124; -- 福佳白啤酒 330ml*6瓶
UPDATE food SET cover_img = "/images/foods/125.jpg" WHERE food_id = 125; -- 三顿半精品速溶咖啡 8颗装
UPDATE food SET cover_img = "/images/foods/126.jpg" WHERE food_id = 126; -- 喜茶轻感多肉葡萄气泡水 480ml*4瓶
UPDATE food SET cover_img = "/images/foods/127.jpg" WHERE food_id = 127; -- 五粮液52度浓香型 100ml
UPDATE food SET cover_img = "/images/foods/128.jpg" WHERE food_id = 128; -- 红富士苹果 1kg
UPDATE food SET cover_img = "/images/foods/129.jpg" WHERE food_id = 129; -- 突尼斯软籽石榴 500g
UPDATE food SET cover_img = "/images/foods/130.jpg" WHERE food_id = 130; -- 泰国金枕榴莲肉 300g
UPDATE food SET cover_img = "/images/foods/131.jpg" WHERE food_id = 131; -- 库尔勒香梨 1kg
UPDATE food SET cover_img = "/images/foods/132.jpg" WHERE food_id = 132; -- 泰国山竹 500g
UPDATE food SET cover_img = "/images/foods/133.jpg" WHERE food_id = 133; -- 国产牛油果 3个
UPDATE food SET cover_img = "/images/foods/134.jpg" WHERE food_id = 134; -- 红提葡萄 500g
UPDATE food SET cover_img = "/images/foods/135.jpg" WHERE food_id = 135; -- 云南蜜柚 1个
UPDATE food SET cover_img = "/images/foods/136.jpg" WHERE food_id = 136; -- 国产蓝莓 125g*2盒
UPDATE food SET cover_img = "/images/foods/137.jpg" WHERE food_id = 137; -- 大白菜 1棵
UPDATE food SET cover_img = "/images/foods/138.jpg" WHERE food_id = 138; -- 新鲜百合 3头
UPDATE food SET cover_img = "/images/foods/139.jpg" WHERE food_id = 139; -- 嫩莴笋 2根
UPDATE food SET cover_img = "/images/foods/140.jpg" WHERE food_id = 140; -- 新鲜枸杞芽 200g
UPDATE food SET cover_img = "/images/foods/141.jpg" WHERE food_id = 141; -- 铁棍山药 500g
UPDATE food SET cover_img = "/images/foods/142.jpg" WHERE food_id = 142; -- 新鲜毛豆 500g
UPDATE food SET cover_img = "/images/foods/143.jpg" WHERE food_id = 143; -- 温氏土鸡 1只约1.2kg
UPDATE food SET cover_img = "/images/foods/144.jpg" WHERE food_id = 144; -- 正大蟹味棒 200g*2包
UPDATE food SET cover_img = "/images/foods/145.jpg" WHERE food_id = 145; -- 大成姐妹花鸡翅中 500g
UPDATE food SET cover_img = "/images/foods/146.jpg" WHERE food_id = 146; -- 恒都肥牛卷 300g*2盒
UPDATE food SET cover_img = "/images/foods/147.jpg" WHERE food_id = 147; -- 凤祥鸡腿肉排 400g
UPDATE food SET cover_img = "/images/foods/148.jpg" WHERE food_id = 148; -- 新希望巴氏杀菌鲜牛奶 950ml
UPDATE food SET cover_img = "/images/foods/149.jpg" WHERE food_id = 149; -- 春雪鸡米花 400g
UPDATE food SET cover_img = "/images/foods/150.jpg" WHERE food_id = 150; -- 蒙牛特仑苏有机纯牛奶 250ml*12盒
UPDATE food SET cover_img = "/images/foods/151.jpg" WHERE food_id = 151; -- 得利斯德式烤肠 500g
UPDATE food SET cover_img = "/images/foods/152.jpg" WHERE food_id = 152; -- 天福号酱肘子 300g
UPDATE food SET cover_img = "/images/foods/153.jpg" WHERE food_id = 153; -- 乐事薯片原味 200g
UPDATE food SET cover_img = "/images/foods/154.jpg" WHERE food_id = 154; -- 徐福记沙琪玛 468g
UPDATE food SET cover_img = "/images/foods/155.jpg" WHERE food_id = 155; -- 盐津铺子辣条大礼包 608g
UPDATE food SET cover_img = "/images/foods/156.jpg" WHERE food_id = 156; -- 奥利奥巧克卷 146g
UPDATE food SET cover_img = "/images/foods/157.jpg" WHERE food_id = 157; -- 良品铺子坚果炒货礼盒 688g
UPDATE food SET cover_img = "/images/foods/158.jpg" WHERE food_id = 158; -- 有友泡椒凤爪 208g
UPDATE food SET cover_img = "/images/foods/159.jpg" WHERE food_id = 159; -- 旺旺仙贝 540g
UPDATE food SET cover_img = "/images/foods/160.jpg" WHERE food_id = 160; -- 卡乐比水果麦片 500g
UPDATE food SET cover_img = "/images/foods/161.jpg" WHERE food_id = 161; -- 桂格即食燕麦片 800g（2包）
UPDATE food SET cover_img = "/images/foods/162.jpg" WHERE food_id = 162; -- 百草味每日坚果礼盒 750g
UPDATE food SET cover_img = "/images/foods/163.jpg" WHERE food_id = 163; -- 东北长粒香米 5kg
UPDATE food SET cover_img = "/images/foods/164.jpg" WHERE food_id = 164; -- 李锦记蒸鱼豉油 410ml
UPDATE food SET cover_img = "/images/foods/165.jpg" WHERE food_id = 165; -- 六必居麻酱 450g
UPDATE food SET cover_img = "/images/foods/166.jpg" WHERE food_id = 166; -- 海底捞番茄火锅底料 200g*3包
UPDATE food SET cover_img = "/images/foods/167.jpg" WHERE food_id = 167; -- 草原红太阳麻酱火锅蘸料 160g*3袋
UPDATE food SET cover_img = "/images/foods/168.jpg" WHERE food_id = 168; -- 吉香居下饭酱 250g*2瓶
UPDATE food SET cover_img = "/images/foods/169.jpg" WHERE food_id = 169; -- 加多宝凉茶 310ml*12罐
UPDATE food SET cover_img = "/images/foods/170.jpg" WHERE food_id = 170; -- 丹丹郫县豆瓣酱 500g
UPDATE food SET cover_img = "/images/foods/171.jpg" WHERE food_id = 171; -- 十月稻田五常大米 5kg
UPDATE food SET cover_img = "/images/foods/172.jpg" WHERE food_id = 172; -- 必品阁王饺子 白菜猪肉 600g
UPDATE food SET cover_img = "/images/foods/173.jpg" WHERE food_id = 173; -- 三全儿童水饺 260g（12个）
UPDATE food SET cover_img = "/images/foods/174.jpg" WHERE food_id = 174; -- 广州酒家利口福叉烧包 300g（4个）
UPDATE food SET cover_img = "/images/foods/175.jpg" WHERE food_id = 175; -- 日清方便面 UFO炒面 132g*5包
UPDATE food SET cover_img = "/images/foods/176.jpg" WHERE food_id = 176; -- 农心辛拉面杯面 69g*5杯
UPDATE food SET cover_img = "/images/foods/177.jpg" WHERE food_id = 177; -- 满小饱肥汁米线 305g*3袋
UPDATE food SET cover_img = "/images/foods/178.jpg" WHERE food_id = 178; -- 空刻意面番茄肉酱 250g*2份
UPDATE food SET cover_img = "/images/foods/179.jpg" WHERE food_id = 179; -- 大希地黑椒牛排 130g*4片
UPDATE food SET cover_img = "/images/foods/180.jpg" WHERE food_id = 180; -- 必品阁泡菜 500g
UPDATE food SET cover_img = "/images/foods/181.jpg" WHERE food_id = 181; -- 农夫山泉饮用天然水 550ml*24瓶
UPDATE food SET cover_img = "/images/foods/182.jpg" WHERE food_id = 182; -- 怡宝纯净水 596ml*12瓶
UPDATE food SET cover_img = "/images/foods/183.jpg" WHERE food_id = 183; -- 康师傅冰红茶 500ml*6瓶
UPDATE food SET cover_img = "/images/foods/184.jpg" WHERE food_id = 184; -- 统一阿萨姆奶茶 500ml*6瓶
UPDATE food SET cover_img = "/images/foods/185.jpg" WHERE food_id = 185; -- 雪碧清爽柠檬味 500ml*6瓶
UPDATE food SET cover_img = "/images/foods/186.jpg" WHERE food_id = 186; -- RIO锐澳微醺预调酒 330ml*3罐
UPDATE food SET cover_img = "/images/foods/187.jpg" WHERE food_id = 187; -- 百威啤酒 500ml*6罐
UPDATE food SET cover_img = "/images/foods/188.jpg" WHERE food_id = 188; -- 科罗娜啤酒 330ml*6瓶
UPDATE food SET cover_img = "/images/foods/189.jpg" WHERE food_id = 189; -- 星巴克VIA速溶咖啡 4条装
UPDATE food SET cover_img = "/images/foods/190.jpg" WHERE food_id = 190; -- 海南金煌芒果 2个
UPDATE food SET cover_img = "/images/foods/191.jpg" WHERE food_id = 191; -- 智利进口车厘子 500g
UPDATE food SET cover_img = "/images/foods/192.jpg" WHERE food_id = 192; -- 宁夏中卫硒砂瓜 1个约5kg
UPDATE food SET cover_img = "/images/foods/193.jpg" WHERE food_id = 193; -- 正宗阳山水蜜桃 4个
UPDATE food SET cover_img = "/images/foods/194.jpg" WHERE food_id = 194; -- 云南墨江紫米 1kg
UPDATE food SET cover_img = "/images/foods/195.jpg" WHERE food_id = 195; -- 鲜活大明虾 400g 约20只
UPDATE food SET cover_img = "/images/foods/196.jpg" WHERE food_id = 196; -- 亿滋奥利奥夹心饼干 388g（2包）
UPDATE food SET cover_img = "/images/foods/197.jpg" WHERE food_id = 197; -- 好丽友好友趣薯片 175g
UPDATE food SET cover_img = "/images/foods/198.jpg" WHERE food_id = 198; -- 海底捞零食大礼包 600g
UPDATE food SET cover_img = "/images/foods/199.jpg" WHERE food_id = 199; -- 三只松鼠夏威夷果礼盒 500g
UPDATE food SET cover_img = "/images/foods/200.jpg" WHERE food_id = 200; -- 王老吉润喉糖 32g*3盒
UPDATE food SET cover_img = "/images/foods/201.jpg" WHERE food_id = 201; -- 每日黑巧瑞士进口巧克力 300g
UPDATE food SET cover_img = "/images/foods/202.jpg" WHERE food_id = 202; -- 海底捞自热米饭 菌菇牛肉 310g
UPDATE food SET cover_img = "/images/foods/203.jpg" WHERE food_id = 203; -- 日清方便面 合味道海鲜风味 74g*6杯
UPDATE food SET cover_img = "/images/foods/204.jpg" WHERE food_id = 204; -- 必品阁玉米热狗 360g（9根）
UPDATE food SET cover_img = "/images/foods/205.jpg" WHERE food_id = 205; -- 大希地鸡块 400g
UPDATE food SET cover_img = "/images/foods/206.jpg" WHERE food_id = 206; -- 海底捞自热烧烤 280g
UPDATE food SET cover_img = "/images/foods/207.jpg" WHERE food_id = 207; -- 小肥羊清汤火锅底料 200g*2包
UPDATE food SET cover_img = "/images/foods/208.jpg" WHERE food_id = 208; -- 农心部队锅方便面 119g*5包
UPDATE food SET cover_img = "/images/foods/209.jpg" WHERE food_id = 209; -- 三全茴香小油条 300g
UPDATE food SET cover_img = "/images/foods/210.jpg" WHERE food_id = 210; -- 日清意面 奶油培根风味 207g*2份
UPDATE food SET cover_img = "/images/foods/211.jpg" WHERE food_id = 211; -- 海底捞菌汤火锅底料 200g*2包
UPDATE food SET cover_img = "/images/foods/212.jpg" WHERE food_id = 212; -- 白家陈记勾魂米线 282g*3桶
UPDATE food SET cover_img = "/images/foods/213.jpg" WHERE food_id = 213; -- 必品阁王饺子 猪肉大葱 600g
UPDATE food SET cover_img = "/images/foods/214.jpg" WHERE food_id = 214; -- 三全春卷 300g（20根）
UPDATE food SET cover_img = "/images/foods/215.jpg" WHERE food_id = 215; -- 湾仔码头水饺 鲜肉荠菜 540g
UPDATE food SET cover_img = "/images/foods/216.jpg" WHERE food_id = 216; -- 空刻意面 黑椒牛柳风味 270g*2份